# Generated by Django 3.0.8 on 2020-08-11 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200810_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
